### ISSUE TITLE
timeouts on ohio's render

### ISSUE THREAD

**Issue by igor47** [usdigitalresponse/arpa-reporter#240]
we discussed the issue here: https://usdigitalresponse.slack.com/archives/C031R1Y49KL/p1650992016937089

saw it again this morning. here are some relevant log snippets (i removed the non-relevant lines):

```
May 12 08:09:01 AM  Rewriting GET /login to /index.html
May 12 08:09:01 AM  ::ffff:10.207.217.69 - - [12/May/2022:15:09:01 +0000] "GET /login HTTP/1.1" 200 1485
May 12 08:09:02 AM  ::ffff:10.206.27.224 - - [12/May/2022:15:09:02 +0000] "GET /api/health HTTP/1.1" 200 16
May 12 08:09:02 AM  ::ffff:10.207.209.69 - - [12/May/2022:15:09:02 +0000] "GET /css/app.edc339d9.css HTTP/1.1" 200 2733
May 12 08:09:02 AM  ::ffff:10.207.217.69 - - [12/May/2022:15:09:02 +0000] "GET /js/app.3d966fd5.js HTTP/1.1" 200 69045
May 12 08:09:02 AM  ::ffff:10.207.237.63 - - [12/May/2022:15:09:02 +0000] "GET /js/chunk-vendors.cb5c7011.js HTTP/1.1" 200 576845
May 12 08:09:02 AM  (node:70) UnhandledPromiseRejectionWarning: Error: select "users"."id", "users"."email", "users"."role", "users"."agency_id", "users"."tags", "roles"."rules" from "users" inner join "roles" on "roles"."name" = "users"."role" where "users"."id" = $1 - Connection terminated unexpectedly    at Connection.<anonymous> (/opt/render/project/src/node_modules/pg/lib/client.js:132:73)    at Object.onceWrapper (events.js:482:28)    at Connection.emit (events.js:376:20)    at Connection.emit (domain.js:470:12)    at Socket.<anonymous> (/opt/render/project/src/node_modules/pg/lib/connection.js:57:12)    at Socket.emit (events.js:376:20)    at Socket.emit (domain.js:470:12)    at TCP.<anonymous> (net.js:673:12)
May 12 08:09:02 AM  (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
May 12 08:09:02 AM  Connection Error: Connection ended unexpectedly
May 12 08:09:02 AM  ::ffff:10.207.10.253 - - [12/May/2022:15:09:02 +0000] "GET /favicon.ico HTTP/1.1" 200 4286
May 12 08:09:07 AM  ::ffff:10.206.27.224 - - [12/May/2022:15:09:07 +0000] "GET /api/health HTTP/1.1" 200 16
May 12 08:09:12 AM  ::ffff:10.206.27.224 - - [12/May/2022:15:09:12 +0000] "GET /api/health HTTP/1.1" 200 16
May 12 08:09:14 AM  ::ffff:10.207.10.253 - - [12/May/2022:15:09:14 +0000] "GET / HTTP/1.1" 200 1485

May 12 08:10:17 AM  Rewriting GET /login to /index.html
May 12 08:10:17 AM  ::ffff:10.207.237.63 - - [12/May/2022:15:10:17 +0000] "GET /login HTTP/1.1" 200 1485
May 12 08:10:18 AM  ::ffff:10.207.10.253 - - [12/May/2022:15:10:18 +0000] "GET /favicon.ico HTTP/1.1" 200 4286

May 12 08:12:09 AM  Connection Error: Connection ended unexpectedly
May 12 08:12:09 AM  ::ffff:10.207.209.69 - - [12/May/2022:15:12:09 +0000] "GET /api/sessions HTTP/1.1" 200 101
May 12 08:12:12 AM  ::ffff:10.206.27.224 - - [12/May/2022:15:12:12 +0000] "GET /api/health HTTP/1.1" 200 16
May 12 08:12:15 AM  ::ffff:10.207.209.69 - - [12/May/2022:15:12:15 +0000] "GET /api/sessions HTTP/1.1" 200 101
May 12 08:12:16 AM  ::ffff:10.207.237.63 - - [12/May/2022:15:12:16 +0000] "GET /api/uploads HTTP/1.1" 200 14
May 12 08:12:16 AM  ::ffff:10.207.237.63 - - [12/May/2022:15:12:16 +0000] "GET /api/projects HTTP/1.1" 200 15
May 12 08:12:16 AM  ::ffff:10.207.217.69 - - [12/May/2022:15:12:16 +0000] "GET /api/configuration HTTP/1.1" 200 30649
May 12 08:12:16 AM  ::ffff:10.207.217.69 - - [12/May/2022:15:12:16 +0000] "GET /api/reporting_periods HTTP/1.1" 200 12409
May 12 08:12:16 AM  ::ffff:10.207.10.253 - - [12/May/2022:15:12:16 +0000] "GET /api/agencies HTTP/1.1" 200 11223
May 12 08:12:16 AM  ::ffff:10.207.10.253 - - [12/May/2022:15:12:16 +0000] "GET /api/subrecipients HTTP/1.1" 200 20
May 12 08:12:16 AM  ::ffff:10.207.209.69 - - [12/May/2022:15:12:16 +0000] "GET /api/application_settings HTTP/1.1" 200 617

May 12 08:13:18 AM  ::ffff:10.207.217.69 - - [12/May/2022:15:13:18 +0000] "GET /api/sessions HTTP/1.1" 200 101
May 12 08:13:18 AM  ::ffff:10.207.217.69 - - [12/May/2022:15:13:18 +0000] "GET /api/configuration HTTP/1.1" 200 30649
May 12 08:13:18 AM  ::ffff:10.207.209.69 - - [12/May/2022:15:13:18 +0000] "GET /api/agencies HTTP/1.1" 200 11223
May 12 08:13:18 AM  ::ffff:10.207.217.69 - - [12/May/2022:15:13:18 +0000] "GET /api/application_settings HTTP/1.1" 200 617
May 12 08:13:18 AM  ::ffff:10.207.209.69 - - [12/May/2022:15:13:18 +0000] "GET /api/uploads HTTP/1.1" 200 14
May 12 08:13:19 AM  ::ffff:10.207.209.69 - - [12/May/2022:15:13:19 +0000] "GET /api/reporting_periods HTTP/1.1" 200 12409
May 12 08:13:19 AM  ::ffff:10.207.209.69 - - [12/May/2022:15:13:19 +0000] "GET /api/subrecipients HTTP/1.1" 200 20
May 12 08:13:19 AM  ::ffff:10.207.209.69 - - [12/May/2022:15:13:19 +0000] "GET /api/projects HTTP/1.1" 200 15

May 12 08:14:10 AM  Rewriting GET /login to /index.html

May 12 08:15:41 AM  ::ffff:10.207.209.69 - - [12/May/2022:15:15:41 +0000] "GET /api/sessions HTTP/1.1" 200 101
May 12 08:15:41 AM  ::ffff:10.207.10.253 - - [12/May/2022:15:15:41 +0000] "GET /api/projects HTTP/1.1" 200 15
May 12 08:15:41 AM  ::ffff:10.207.209.69 - - [12/May/2022:15:15:41 +0000] "GET /api/uploads HTTP/1.1" 200 14
May 12 08:15:41 AM  ::ffff:10.207.217.69 - - [12/May/2022:15:15:41 +0000] "GET /api/application_settings HTTP/1.1" 200 617
May 12 08:15:41 AM  ::ffff:10.207.10.253 - - [12/May/2022:15:15:41 +0000] "GET /api/reporting_periods HTTP/1.1" 200 12409
May 12 08:15:41 AM  ::ffff:10.207.237.63 - - [12/May/2022:15:15:41 +0000] "GET /api/configuration HTTP/1.1" 200 30649
May 12 08:15:41 AM  ::ffff:10.207.10.253 - - [12/May/2022:15:15:41 +0000] "GET /api/subrecipients HTTP/1.1" 200 20
May 12 08:15:41 AM  ::ffff:10.207.237.63 - - [12/May/2022:15:15:41 +0000] "GET /api/agencies HTTP/1.1" 200 11223
```

i'm going to guess that the initial traceback from knex/postgres is related to https://github.com/knex/knex/issues/3523 where someone says:
> One can probably work around this issue by setting minimum pool size to 0 and set idle timeout to be like 5 minutes or so. In that way connections will be discarded from pool before that.

and, googling for the "connection ended unexpectedly" error, i find https://github.com/strapi/strapi/issues/8117 where the author also suggests messing with connection pool settings to work around the problem.

**Comment by igor47** [comment]
oh, i guess another option is to have the `/api/health` endpoint actually do a DB query... that would probably keep the connection alive, and would be a more representative health check, since the app does not work without the DB. ummm.... maybe i'll do both?
